---
# See /etc/ansible/hosts or -i hosts
- hosts: controllers
  remote_user: root
  roles:
    - docker-host

#- hosts: containers
#  gather_facts: no
#  remote_user: root
#  roles:
#    - docker-container
