#!/usr/bin/dh-exec

usr/include/pacemaker/crm/attrd.h
usr/include/pacemaker/crm/common/ipc.h
usr/include/pacemaker/crm/common/iso8601.h
usr/include/pacemaker/crm/common/logging.h
usr/include/pacemaker/crm/common/mainloop.h
usr/include/pacemaker/crm/common/util.h
usr/include/pacemaker/crm/common/xml.h
usr/include/pacemaker/crm/compatibility.h
usr/include/pacemaker/crm/crm.h
usr/include/pacemaker/crm/error.h
usr/include/pacemaker/crm/msg_xml.h
usr/include/pacemaker/crm/transition.h
usr/include/pacemaker/crm_config.h usr/include/${DEB_HOST_MULTIARCH}/pacemaker
usr/lib/*/libcrmcommon.so
usr/lib/*/libtransitioner.so
usr/lib/*/pkgconfig/pacemaker.pc 
